### ISSUE TITLE
Add omitAdditionalProps to clean-tag

### ISSUE THREAD

**Issue by just-be-dev** [styled-system/extras#2]
We've got a lot of cases where props are ending up in the dom. We're trying to go through and clean those up, but adding things to `omitProps` means it doesn't get all the defaults. I'd like to be able to add props to omit _in addition to_ the defaults. 

I'll have a PR shortly.

**Comment by jxnblk** [comment]
If you're doing that level of customization, I'd definitely recommend forking this or keeping the clean-tag source in your application

**Comment by just-be-dev** [comment]
Hmmm... I'm not sure I really want to take it that far. I'll look into an alternative solution.
