### ISSUE TITLE
add `outline` support

### ISSUE THREAD

**Issue by peduarte** [styled-system/extras#22]
Yo,

How do you feel about adding `outline` properties?

They could map to the same theme objects as `border`.

I use `outline` often when I don't the border to impact the computed height/width of my elements.

**Comment by jxnblk** [comment]
FWIW, with `@styled-system/css` you *can* use `theme.outline` to define a scale for properties that aren't explicitly defined – any CSS property should fallback to `theme[cssProperty]` like this

**Comment by peduarte** [comment]
My use case is more like `outlineColor` so it'd be the eq of `borderColor`, which maps to `theme.colors`

**Comment by jxnblk** [comment]
Without any changes to the library, you *should* be able to alias the colors to `theme.outlineColor = theme.colors`

**Comment by peduarte** [comment]
Ohhh cheeky! 

Thanks! Will close this and leave it up to you to decide if you wanna add `outline` or not 👍
