### ISSUE TITLE
css package: sizes key?

### ISSUE THREAD

**Issue by kevinSuttle** [styled-system/extras#23]
I'm seeing a delta between the `css` package [doc](https://github.com/styled-system/extras/blob/424b8e8c8ba47b3eae5fd257e9761a1253cef495/packages/css/README.md#theme-keys) 
<img width="372" alt="Image 2019-05-16 at 12 47 53 PM" src="https://user-images.githubusercontent.com/95672/57872293-5dfd4a00-77d9-11e9-85ba-f3e42ed1ebc3.png">

And the [reference table](https://styled-system.com/table#layout) in Style System's docs.
![Screen Shot 2019-05-16 at 12 53 02 PM](https://user-images.githubusercontent.com/95672/57872593-06aba980-77da-11e9-8528-654430315fd9.png)

<img width="868" alt="Screen Shot 2019-05-16 at 12 56 55 PM" src="https://user-images.githubusercontent.com/95672/57872651-24790e80-77da-11e9-8848-b2dddf9da023.png">

I tried using `sizes` in `styled-system`, but found it didn't work yet. Are there plans to unify this?

**Comment by kevinSuttle** [comment]
Closing due to v5's updating https://styled-system.com/table#layout

**Comment by jxnblk** [comment]
Sorry, thought I'd responded to this... but yeah, since it was a breaking change, it required a major version bump – more background here https://github.com/system-ui/theme-specification/pull/2
