### ISSUE TITLE
Key is being appended to the selector causing responsive arrays to fail

### ISSUE THREAD

**Issue by johngrasty** [styled-system/extras#8]
Hey,
I'm really enjoying this new CSS prop! Thanks for your work. I'm seeing a failure on some responsive arrays where a number is being appended. For example:

```
<style data-emotion="css">.css-wnbiem-NavLink-StyledSubNavLink 0{padding:4px;}</style>
<style data-emotion="css">@media screen and (min-width:480px){.css-wnbiem-NavLink-StyledSubNavLink 1{padding:4px;}}</style>
<style data-emotion="css">@media screen and (min-width:750px){.css-wnbiem-NavLink-StyledSubNavLink 2{padding:16px;}}</style>
```

If I can find some time, I'll will try to put together a minimal example with demonstrates this.

**Comment by jxnblk** [comment]
I *think* I was running into the same thing, but please reopen this if you're seeing the same issue with `1.0.3`

**Comment by johngrasty** [comment]
This seems to take care of the problem. Thanks!
